juiceShop:
  # -- Specifies how many JuiceShop instances MultiJuicer should start at max. Set to -1 to remove the max Juice Shop instance cap
  maxInstances: 20
  # -- Specify a custom Juice Shop config.yaml. See the JuiceShop Config Docs for more detail: https://pwning.owasp-juice.shop/part1/customization.html#yaml-configuration-file
  # @default -- See values.yaml for full details
  config: |
    application:
      logo: https://raw.githubusercontent.com/iteratec/multi-juicer/master/images/multijuicer-icon-only-padding.png
      favicon: https://raw.githubusercontent.com/iteratec/multi-juicer/master/juice-balancer/ui/public/favicon.ico
      showVersionNumber: false
      showGitHubLinks: false
    challenges:
      showHints: true
    hackingInstructor:
      isEnabled: true
    ctf:
      showFlagsInNotifications: false
