# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: nginx

balancer:
  metrics:
    enabled: true
    dashboards:
      enabled: true
    serviceMonitor:
      enabled: true
    basicAuth:
      password: GNVUfA2WyhAVGDXZbjCU

juiceShop:
  # -- Specifies how many JuiceShop instances MultiJuicer should start at max. Set to -1 to remove the max Juice Shop instance cap
  maxInstances: 20
  # -- Specify a custom Juice Shop config.yaml. See the JuiceShop Config Docs for more detail: https://pwning.owasp-juice.shop/part1/customization.html#yaml-configuration-file
  # @default -- See values.yaml for full details
  config: |
    application:
      domain: patsa.org
      name: PA TSA Cybersecurity Shop
      logo: https://raw.githubusercontent.com/incyclesoftware/multi-juicer/features/tsa-config/images/tsa.svg
      favicon: https://raw.githubusercontent.com/incyclesoftware/multi-juicer/features/tsa-config/images/tsa.svg
      showVersionNumber: false
      showGitHubLinks: false
      altcoinName: TSAcoin
      privacyContactEmail: privacy@patsa.org
      chatBot:
        name: Patsa
        avatar: https://raw.githubusercontent.com/incyclesoftware/multi-juicer/features/tsa-config/images/TSA.png
      social:
        twitterUrl: #
        facebookUrl: #
        slackUrl: #
        pressKitUrl: #
        questionnaireUrl: ~
      welcomeBanner:
        showOnFirstStart: false
        title: PA TSA Cybersecurity Shop
        message: <p>Welcome to the PA TSA Cybersecurity Shop</p>
      cookieConsent:
        message: 'This website uses cookies to ensure you get the best tracking experience.'
      securityTxt:
        contact: mailto:donotreply@patsa.org
    challenges:
      showHints: false
      showMitigations: false
      codingChallengesEnabled: never
      overwriteUrlForProductTamperingChallenge: http://patsa.org/
      xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/148688836&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
      safetyOverride: false
      showFeedbackButtons: false
    hackingInstructor:
      isEnabled: false
      avatarImage: https://raw.githubusercontent.com/incyclesoftware/multi-juicer/features/tsa-config/images/TSA.png
    ctf:
      showFlagsInNotifications: false
# grafana:
#   adminPassword: "N!K&brr&i4dsn*v8*Jn"



  # --set balancer.metrics.enabled=true \
  # --set balancer.metrics.dashboards.enabled=true \
  # --set balancer.metrics.serviceMonitor.enabled=true \
  # --set balancer.metrics.basicAuth.password="GNVUfA2WyhAVGDXZbjCU" \
  # --set grafana.adminPassword="N!K&brr&i4dsn*v8*Jn" \
  # --set juiceShop.maxInstances=20 \
  # # --set juiceShop.config= \
  # # --set ingress.enabled=true \
  # # --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
  # # --set ingress.hosts[0].host="cybersecurity.tsa-challange.org" \
  # # --set ingress.hosts[0].paths[0]="/"