kind: Service
apiVersion: v1
metadata:
  name: monitoring-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: monitoring    
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
